---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-prod-pv
  labels:
    name: postgresql-prod-pv
spec:
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteMany
  capacity:
    storage: "5Gi"
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.1.55.201
    path: "/export/kubernetes/postgresql/postgresql-pv-01"