# Not secure to use password in ConfigMap
---
apiVersion: v1
kind: Namespace
metadata:
  name: database-prod
  labels:
    name: database-prod
    env: prod

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresql-configmap
  namespace: database-prod
  labels:
    name: postgresql-configmap
    app: postgresql
    env: prod
data:
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  PGDATA: /var/lib/postgresql/data/pgdata

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-prod-pv
  labels:
    name: postgresql-prod-pv
spec:
  storageClassName: nfs
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  accessModes: 
    - ReadWriteMany
  capacity:
    storage: "5Gi"
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: 10.1.55.201
    path: "/export/kubernetes/postgresql/postgresql-pv-01"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-prod-pvc
  namespace: database-prod
  labels:
    name: postgresql-prod-pvc
spec:
  storageClassName: nfs
  accessModes: 
    - ReadWriteMany
  resources:
    requests:
      storage: "5Gi"
  selector:
    matchLabels:
      name: postgresql-prod-pv

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: database-prod
  labels:
    name: postgresql
    app: postgresql
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      namespace: database-prod
      labels:
        app: postgresql
        env: prod
    spec:      
      containers:
      - name: postgres
        image: postgres:14-alpine
        envFrom:
          - configMapRef:
              name: postgresql-configmap
        ports:
        - name: postgresql-port
          containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: postgresql-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-storage
        persistentVolumeClaim:
          claimName: postgresql-prod-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: database-prod
  labels:
    name: postgresql-service
    app: postgresql-service
    env: prod
spec:
  type: ClusterIP
  selector:
    app: postgresql
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
