---
apiVersion: v1
kind: Service
metadata:
  name: postgresql-service
  namespace: database-prod
  labels:
    name: postgresql-service
    app: postgresql-service
    env: prod
spec:
  type: LoadBalancer
  selector:
    app: postgresql
  ports:
  - port: 5432
    protocol: TCP
